name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "fix/vite-config" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Vite
        run: |
          npm run build
          # Create the dragonfly-expense-hub directory in dist
          mkdir -p dist/dragonfly-expense-hub/assets
          # Copy all files from dist to the subdirectory, excluding the subdirectory itself
          find dist -maxdepth 1 -type f -exec cp {} dist/dragonfly-expense-hub/ \;
          # Copy assets directory
          cp -r dist/assets/* dist/dragonfly-expense-hub/assets/
          # Copy PWA files to the correct location if they exist
          [ -f public/icon-192x192.png ] && cp public/icon-192x192.png dist/dragonfly-expense-hub/
          [ -f public/icon-512x512.png ] && cp public/icon-512x512.png dist/dragonfly-expense-hub/
          [ -f public/screenshot-desktop.png ] && cp public/screenshot-desktop.png dist/dragonfly-expense-hub/
          [ -f public/screenshot-mobile.png ] && cp public/screenshot-mobile.png dist/dragonfly-expense-hub/
          [ -f public/favicon.ico ] && cp public/favicon.ico dist/dragonfly-expense-hub/
          [ -f public/site.webmanifest ] && cp public/site.webmanifest dist/dragonfly-expense-hub/
          # Move everything to the root for GitHub Pages
          cp -r dist/dragonfly-expense-hub/* .
        env:
          NODE_ENV: production
          VITE_BASE_URL: /dragonfly-expense-hub/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 